---
- name: Play to start nginx service
  hosts: rs
  tasks:
    - name: Install nginx on ubuntu
      apt: 
        name: nginx 
        state: installed
      when: ansible_os_family == "Debian"

    - name: Install nginx on centos
      yum: 
        name: nginx 
        state: installed
      when: ansible_os_family == "Redhat"

    - name: Start nginx
      service: name=nginx state=started enabled=on
